[package]
name = "playmusic"
version = "0.1.0"
authors = ["Ryan Petschek <petschekr@gmail.com>"]

[dependencies]
reqwest = "0.8.5"
hyper = "0.11.22"
openssl = "0.9.20"
ring = "0.12.1"
base64 = "0.7.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
